# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sugar_model <- function(ndays, Temp, PF, HN0, D0, D00, LR0, RmN, RmS, RmR, needles_R, height_R, wall_R, roots_R, use_R, release_R, storage_grows, mycorrhiza_threshold, Ad0_R, lambda_R, Q10d, Q10s, carbon_sugar, needles_mass, common_R, resistance_R) {
    .Call('_CASSIA_sugar_model', PACKAGE = 'CASSIA', ndays, Temp, PF, HN0, D0, D00, LR0, RmN, RmS, RmR, needles_R, height_R, wall_R, roots_R, use_R, release_R, storage_grows, mycorrhiza_threshold, Ad0_R, lambda_R, Q10d, Q10s, carbon_sugar, needles_mass, common_R, resistance_R)
}

