# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
CASSIA_yearly <- function(start_year, end_year, weather, GPP_ref, pPREL, pCASSIA_parameters, pCASSIA_common, pCASSIA_ratios, pCASSIA_sperling, needle_mass_in, Throughfall, nitrogen_capacity, settings) {
    .Call(`_CASSIA_CASSIA_yearly`, start_year, end_year, weather, GPP_ref, pPREL, pCASSIA_parameters, pCASSIA_common, pCASSIA_ratios, pCASSIA_sperling, needle_mass_in, Throughfall, nitrogen_capacity, settings)
}

replace_value_DataFrame <- function(df, value, ref) {
    .Call(`_CASSIA_replace_value_DataFrame`, df, value, ref)
}

#' @export
CASSIA_soil <- function(start_year, end_year, weather, GPP_ref, pPREL, pCASSIA_parameters, pCASSIA_common, pCASSIA_ratios, pCASSIA_sperling, parameters_R, needle_mass_in, Throughfall, nitrogen_capacity, trenching_year, settings) {
    .Call(`_CASSIA_CASSIA_soil`, start_year, end_year, weather, GPP_ref, pPREL, pCASSIA_parameters, pCASSIA_common, pCASSIA_ratios, pCASSIA_sperling, parameters_R, needle_mass_in, Throughfall, nitrogen_capacity, trenching_year, settings)
}

xylogenesis_wrapper <- function(no_day, day, pCASSIA_parameters, pCASSIA_common, pCASSIA_sperling, extras_sperling, xylogenesis_option, environmental_effect_xylogenesis, TAir, n_rows, max_ew_cells, n_E_pot_old, n_W_pot_old, n_M_pot_old, g, en_growth_vector, tau_W_old, carbon_daily_rate_ew, carbon_daily_rate_lw) {
    .Call(`_CASSIA_xylogenesis_wrapper`, no_day, day, pCASSIA_parameters, pCASSIA_common, pCASSIA_sperling, extras_sperling, xylogenesis_option, environmental_effect_xylogenesis, TAir, n_rows, max_ew_cells, n_E_pot_old, n_W_pot_old, n_M_pot_old, g, en_growth_vector, tau_W_old, carbon_daily_rate_ew, carbon_daily_rate_lw)
}

plant_decision <- function(C_roots_NonStruct, N_roots_NonStruct, C_fungal_NonStruct, optimal_root_funga_biomass_ratio, m) {
    .Call(`_CASSIA_plant_decision`, C_roots_NonStruct, N_roots_NonStruct, C_fungal_NonStruct, optimal_root_funga_biomass_ratio, m)
}

myco_decision <- function(N_fungal_NonStruct, C_roots_NonStruct, N_roots_NonStruct, NC_fungal_opt) {
    .Call(`_CASSIA_myco_decision`, N_fungal_NonStruct, C_roots_NonStruct, N_roots_NonStruct, NC_fungal_opt)
}

CASSIA_eeo <- function(start_year, end_year, weather, GPP_ref, pPREL, pCASSIA_parameters, pCASSIA_common, pCASSIA_ratios, pCASSIA_sperling, parameters_R, pPhydro, needle_mass_in, Throughfall, nitrogen_capacity, trenching_year, settings) {
    .Call(`_CASSIA_CASSIA_eeo`, start_year, end_year, weather, GPP_ref, pPREL, pCASSIA_parameters, pCASSIA_common, pCASSIA_ratios, pCASSIA_sperling, parameters_R, pPhydro, needle_mass_in, Throughfall, nitrogen_capacity, trenching_year, settings)
}

growth_wrapper <- function(day, year, TAir, TSoil_A, TSoil_B, Soil_Moisture, PF, GPP_ref, root_as_Ding, xylogenesis_option, environmental_effect_xylogenesis, sD_estim_T_count, pCASSIA_common, pCASSIA_parameters, pCASSIA_ratios, pCASSIA_sperling, extras_sperling, CH, B0, en_pot_growth_old, GPP_mean, GPP_previous_sum, LH_estim, LN_estim, LD_estim, tests, growth_in, last_year_HH, no_day) {
    .Call(`_CASSIA_growth_wrapper`, day, year, TAir, TSoil_A, TSoil_B, Soil_Moisture, PF, GPP_ref, root_as_Ding, xylogenesis_option, environmental_effect_xylogenesis, sD_estim_T_count, pCASSIA_common, pCASSIA_parameters, pCASSIA_ratios, pCASSIA_sperling, extras_sperling, CH, B0, en_pot_growth_old, GPP_mean, GPP_previous_sum, LH_estim, LN_estim, LD_estim, tests, growth_in, last_year_HH, no_day)
}

myco_growth <- function(C_fungal, N_fungal, C_fungal_biomass, C_ecto, a, b, CN_ratio) {
    .Call(`_CASSIA_myco_growth`, C_fungal, N_fungal, C_fungal_biomass, C_ecto, a, b, CN_ratio)
}

mycofon_balence <- function(C_biomass, C_roots, C_fungal, C_ecto, C_roots_NonStruct, N_roots_NonStruct, C_fungal_NonStruct, N_fungal_NonStruct, max_C_from_CASSIA, parameters_R, NH4, NO3, FOM_Norg, T, Tmb, SWC, mycofon_stratergy, trenching) {
    .Call(`_CASSIA_mycofon_balence`, C_biomass, C_roots, C_fungal, C_ecto, C_roots_NonStruct, N_roots_NonStruct, C_fungal_NonStruct, N_fungal_NonStruct, max_C_from_CASSIA, parameters_R, NH4, NO3, FOM_Norg, T, Tmb, SWC, mycofon_stratergy, trenching)
}

uptake_N <- function(N, T, SWC, N_limit, k, SWC_limit) {
    .Call(`_CASSIA_uptake_N`, N, T, SWC, N_limit, k, SWC_limit)
}

uptake_C <- function(C, T, SWC, C_limit, k, SWC_limit) {
    .Call(`_CASSIA_uptake_C`, C, T, SWC, C_limit, k, SWC_limit)
}

Plant_N_Uptake <- function(T, SWC, m, NH4_in, NO3_in, FOM_in, N_limits_R, N_k_R, SWC_limits_R, NH4_on_NO3, demand) {
    .Call(`_CASSIA_Plant_N_Uptake`, T, SWC, m, NH4_in, NO3_in, FOM_in, N_limits_R, N_k_R, SWC_limits_R, NH4_on_NO3, demand)
}

Fungal_N_Uptake <- function(T, SWC, NH4, NO3, FOM_Norg, N_limits_R, N_k_R, SWC_k_R, demand) {
    .Call(`_CASSIA_Fungal_N_Uptake`, T, SWC, NH4, NO3, FOM_Norg, N_limits_R, N_k_R, SWC_k_R, demand)
}

Microbe_Uptake <- function(C_microbe, N_micorbe, C_exudates, C_soil_compartment, NC_microbe_opt, NH4_avaliable, NO3_avaliable, Norg_avaliable, T, SWC, imobilisation, assimilation, N_limits_R, N_k_R, SWC_k_R, SOM_decomposers, FOM_Norg, tests) {
    .Call(`_CASSIA_Microbe_Uptake`, C_microbe, N_micorbe, C_exudates, C_soil_compartment, NC_microbe_opt, NH4_avaliable, NO3_avaliable, Norg_avaliable, T, SWC, imobilisation, assimilation, N_limits_R, N_k_R, SWC_k_R, SOM_decomposers, FOM_Norg, tests)
}

preles_test <- function(weather) {
    .Call(`_CASSIA_preles_test`, weather)
}

repola_test_cpp <- function(pCASSIA_parameters, pCASSIA_sperling) {
    .Call(`_CASSIA_repola_test_cpp`, pCASSIA_parameters, pCASSIA_sperling)
}

respiration_test_cpp <- function(pCASSIA_parameters, pCASSIA_common, pCASSIA_ratios, pCASSIA_sperling, extras_sperling, day, TAir, TSoil, temp_rise, Rm_acclimation, mN_varies, B0) {
    .Call(`_CASSIA_respiration_test_cpp`, pCASSIA_parameters, pCASSIA_common, pCASSIA_ratios, pCASSIA_sperling, extras_sperling, day, TAir, TSoil, temp_rise, Rm_acclimation, mN_varies, B0)
}

printColumnNames <- function(df) {
    invisible(.Call(`_CASSIA_printColumnNames`, df))
}

symphony <- function(params) {
    .Call(`_CASSIA_symphony`, params)
}

symphony_plus <- function(params, Photosynthesis) {
    .Call(`_CASSIA_symphony_plus`, params, Photosynthesis)
}

symphony_plus_daily <- function(params, Photosynthesis, C_plant, C_FOM, N) {
    .Call(`_CASSIA_symphony_plus_daily`, params, Photosynthesis, C_plant, C_FOM, N)
}

